version: "2"
run:
  # NOTE: fix ERRO [linters_context] typechecking error: named files must all be in one directory; have cmd/app and internal/presentation 
  packages-separately: true # パッケージごとに並列実行
  module-run-mode: readonly # モジュールを読み込み専用にする
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - gosec
    - misspell
    - noctx
    - prealloc
    - revive
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/nansystem/go-ddd
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
