services:
  mysql:
    image: mysql:8.0
    container_name: go-ddd-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: go_ddd
      MYSQL_USER: ddduser
      MYSQL_PASSWORD: dddpass
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "ddduser", "-pdddpass"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
    driver: local
