// Code generated by gqlgenc, DO NOT EDIT.

package model

type GetViewerRequest struct {
}

type GetViewerResponse struct {
	Viewer struct {
		Login string `json:"login"`
	} `json:"viewer"`
}

type GetRepositoryRequest struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

type GetRepositoryResponse struct {
	Viewer struct {
		Login string `json:"login"`
	} `json:"viewer"`
	Repository struct {
		ID             string `json:"id"`
		Name           string `json:"name"`
		URL            string `json:"url"`
		Description    string `json:"description"`
		StargazerCount int    `json:"stargazerCount"`
		ForkCount      int    `json:"forkCount"`
		Issues         struct {
			TotalCount int `json:"totalCount"`
			Nodes      []struct {
				ID        string `json:"id"`
				Title     string `json:"title"`
				URL       string `json:"url"`
				CreatedAt string `json:"createdAt"`
				Author    struct {
					Login string `json:"login"`
				} `json:"author"`
			} `json:"nodes"`
		} `json:"issues"`
		PullRequests struct {
			TotalCount int `json:"totalCount"`
			Nodes      []struct {
				ID        string `json:"id"`
				Title     string `json:"title"`
				URL       string `json:"url"`
				CreatedAt string `json:"createdAt"`
				Author    struct {
					Login string `json:"login"`
				} `json:"author"`
			} `json:"nodes"`
		} `json:"pullRequests"`
	} `json:"repository"`
}
